"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import store, { persistor } from "./store/store";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <Toaster
              position="top-right"
              toastOptions={{
                success: {
                  style: {
                    backgroundColor: "green",
                    color: "#fff",
                    padding: "8px",
                    borderRadius: "10px",
                  },
                  icon: "✅",
                },
                error: {
                  style: {
                    backgroundColor: "red",
                    color: "#fff",
                    padding: "8px",
                    borderRadius: "10px",
                  },
                  icon: "❌",
                },
              }}
            />

            {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
